In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

# Importing Datasets on Microbial Consumption

The source of these datasets is the [European Centre for Disease Prevention and Control's Annual 2021 Report](https://www.ecdc.europa.eu/en/data/downloadable-datasets) 

They feature a dataset per [antimicrobial category](https://www.who.int/tools/atc-ddd-toolkit/atc-classification) as defined by the WHO. 

## The WHO's ATC Classification
* The WHO has designed the Anatomical Therapeutic Chemical (ATC) classification system for indexing drug compunds.
* The classification system is divided into five different levels.
* As an example: The 1st level classifies drugs into anatomical groups - see the calssification here.
<img src="Images/who_1st classification.png" alt="My Image" width="800" height="600">
* Given their nature, antimicrobial drugs are classified under letter J.


## The types of antimicrobial drugs discussed here
(needs to be written)

## Community vs Hospital administration
(needs to be written)

## The ECDC's Data Dictionary

* **All country data are shown as they are reported to The European Surveillance System. **
* **Antimicrobial consumption is expressed as the number of defined daily doses (DDD) per 1 000 inhabitants per day.**
* One DDD represents the assumed average maintenance dose per day for a drug used in its main indication by adults
* All data here uploaded referes to different **antibacterials** for systemic use

* EU/EEA refers to the population-weighted mean consumption based on reported or imputed antimicrobial consumption data from all 29 EU/EEA countries, and excludes the United Kingdom. 
* Country adjustments were applied as detailed in the Methods chapter.
* Crude EU/EEA refers to the population-weighted mean consumption based on reported data available for the specific year, with no imputations for missing data or adjustments for change in data source and includes the UK for the years 2012−2019.
* N/A = Not applicable. Trend analyses was not performed and CAGR not calculated because of missing data, changes in the type of data or change in data process. † = Spain reported reimbursement data for 2011-2015 and changed to sales data in 2016.
* Luxembourg changed data process in 2020, which could impact comparability with previous years.
* For details, please refer to the Methods chapter.
* (a) Finland: data include consumption in remote primary healthcare centres and nursing homes.

# Step 1: Loading the Data
## Antimicrobial Data Administered between 2021 and 2022

In [70]:
community_betalactams_main = pd.read_csv('Data/community_betalactams.csv')
community_betalactams_others = pd.read_csv('Data/community_betalactams_others.csv')
community_macrolides_lincosamides_streptogramins= pd.read_csv('Data/community_macrolides_lincosamides_streptogramins.csv')
community_others= pd.read_csv('Data/community_others.csv')
community_quinolones= pd.read_csv('Data/community_quinolones.csv')
community_sulfonamides_trimethoprim= pd.read_csv('Data/community_sulfonamides_trimethoprim.csv')
community_tetracyclines= pd.read_csv('Data/community_tetracyclines.csv')
hospital_betalactams_main = pd.read_csv('Data/hospital_betalactams.csv')
hospital_betalactams_others= pd.read_csv('Data/hospital_betalactams_others.csv')
hospital_carbapenems = pd.read_csv('Data/hospital_carbapenems.csv')
hospital_macrolides_lincosamides_streptogramins = pd.read_csv('Data/hospital_macrolides_lincosamides_streptogramins.csv')
hospital_others = pd.read_csv('Data/hospital_others.csv')
hospital_polymyxins = pd.read_csv('Data/hospital_polymyxins.csv')
hospital_quinolones = pd.read_csv('Data/hospital_quinolones.csv')
hospital_reserve = pd.read_csv('Data/hospital_reserve.csv')
hospital_sulfonamides_trimethoprim = pd.read_csv('Data/hospital_sulfonamides_trimethoprim.csv')
hospital_tetracyclines = pd.read_csv('Data/hospital_tetracyclines.csv')

In [104]:
community_betalactams_main[:]

   Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
3       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
7       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
9        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
11       Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
12      Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
14      Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
15        Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
16       Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
19        Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
20  Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
21       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
25     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
26     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
28       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4

In [72]:
community_betalactams_others[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,1.58,1.95,1.48,1.44,1.41,1.51,1.40,1.27,0.96,1.04,-4.6%,NaN,NaN,NaN
1,Belgium,1.53,1.53,1.42,1.44,1.32,1.17,1.25,1.20,0.80,0.80,-7.0%,NaN,NaN,NaN
2,Bulgaria,2.44,2.80,3.38,3.90,3.84,4.11,4.48,4.28,3.97,4.54,7.2%,NaN,NaN,NaN

In [73]:
community_macrolides_lincosamides_streptogramins[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13
0,Austria,3.19,3.59,3.04,3.06,2.74,2.81,2.25,2.04,1.42,1.39,-8.8%,NaN,NaN
1,Belgium,3.40,3.34,3.40,3.63,3.62,3.41,3.56,3.50,2.65,2.65,-2.7%,NaN,NaN
2,Bulgaria,3.16,3.44,3.93,3.87,3.67,3.82,4.00,4.01,5.72,5.50,6.4%,NaN,NaN

In [74]:
community_others[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,0.28,0.35,0.33,0.33,0.34,0.38,0.35,0.36,0.30,0.22,-2.8%,NaN,NaN,NaN
1,Belgium,2.63,2.71,2.76,2.73,2.75,2.51,2.51,2.60,2.50,2.54,-0.4%,NaN,NaN,NaN
2,Bulgaria,0.00,0.00,0.00,0.00,0.10,0.11,0.02,0.01,0.01,0.01,40.7%,NaN,NaN,NaN

In [75]:
community_quinolones[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13
0,Austria,1.30,1.47,1.30,1.31,1.20,1.23,1.04,0.73,0.57,0.52,-9.7%,NaN,NaN
1,Belgium,2.77,2.64,2.55,2.57,2.40,2.17,1.16,0.57,0.46,0.45,-18.4%,NaN,NaN
2,Bulgaria,2.40,2.52,2.87,2.83,2.78,2.86,2.83,2.76,3.35,3.92,5.6%,NaN,NaN

In [76]:
community_sulfonamides_trimethoprim[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13
0,Austria,0.22,0.23,0.20,0.19,0.20,0.22,0.20,0.22,0.22,0.23,0.6%,NaN,NaN
1,Belgium,NaN,0.27,0.18,0.21,0.20,0.19,0.21,0.21,0.22,0.24,-1.6%,NaN,NaN
2,Bulgaria,0.82,0.83,0.84,0.79,0.78,0.85,0.86,0.78,0.64,0.65,-2.6%,NaN,NaN

In [77]:
community_tetracyclines[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Austria,1.08,1.27,1.06,0.99,0.86,0.63,0.36,0.32,0.28,0.34,-12.1%,NaN,NaN,NaN,NaN,NaN
1,Belgium,2.11,2.16,2.10,2.03,1.99,1.92,1.87,1.86,1.63,1.81,-1.7%,NaN,NaN,NaN,NaN,NaN
2,Bulgaria,1.77,1.76,1.79,1.70,1.68,1.63,1.62,1.68,2.19,2.56,4.2%,NaN,NaN,NaN,NaN,NaN

In [78]:
hospital_betalactams_main[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.69,0.64,0.62,NaN,NaN,NaN,NaN
1,Belgium,0.79,0.75,0.74,0.76,0.75,0.74,0.76,0.74,0.64,0.64,-2.3%,NaN,NaN,NaN
2,Bulgaria,0.11,0.10,0.11,0.10,0.10,0.10,0.11,0.12,0.13,0.12,1.1%,NaN,NaN,NaN

In [79]:
hospital_betalactams_others[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.53,0.49,0.49,NaN,NaN,NaN,NaN
1,Belgium,0.38,0.39,0.38,0.39,0.38,0.37,0.38,0.38,0.33,0.34,-1.1%,NaN,NaN,NaN
2,Bulgaria,0.81,0.77,0.79,0.74,0.97,0.91,0.91,0.94,1.00,1.21,4.6%,NaN,NaN,NaN

In [80]:
hospital_carbapenems[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.11,0.11,0.11,NaN,NaN,NaN,NaN
1,Belgium,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.04,0.04,-2.6%,NaN,NaN,NaN
2,Bulgaria,0.01,0.01,0.01,0.01,0.02,0.03,0.03,0.04,0.10,0.12,32.7%,NaN,NaN,NaN

In [81]:
hospital_macrolides_lincosamides_streptogramins[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.15,0.13,0.11,NaN,NaN,NaN,NaN
1,Belgium,0.10,0.10,0.10,0.11,0.11,0.11,0.11,0.12,0.11,0.09,-1.0%,NaN,NaN,NaN
2,Bulgaria,0.13,0.14,0.14,0.11,0.11,0.11,0.13,0.12,0.23,0.13,0.1%,NaN,NaN,NaN

In [82]:
hospital_others[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.16,0.16,0.18,NaN,NaN,NaN,NaN,NaN
1,Belgium,0.15,0.14,0.14,0.14,0.13,0.13,0.12,0.12,0.11,0.11,-2.7%,NaN,NaN,NaN,NaN
2,Bulgaria,0.01,0.08,0.02,0.10,0.11,0.14,0.18,0.15,0.12,0.08,21.7%,NaN,NaN,NaN,NaN

In [83]:
hospital_polymyxins[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003,NaN,0.002,NaN,NaN,NaN,NaN
1,Belgium,0.003,0.003,0.003,0.003,0.004,0.003,0.003,0.003,0.003,0.002,-2.2%,NaN,NaN,NaN
2,Bulgaria,NaN,NaN,0.001,0.001,0.001,0.001,0.002,0.003,0.003,0.005,33.9%,NaN,NaN,NaN

In [84]:
hospital_quinolones[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.17,0.13,0.12,NaN,NaN,NaN
1,Belgium,0.23,0.22,0.21,0.21,0.20,0.19,0.17,0.16,0.13,0.13,-6.1%,NaN,NaN
2,Bulgaria,0.12,0.11,0.14,0.14,0.15,0.14,0.17,0.17,0.33,0.34,12.4%,NaN,NaN

In [85]:
hospital_reserve[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Time series\n2012-2021,Trend,Compound annual growth rate (CAGR)
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.41,5.10,5.99,NaN,NaN,NaN
1,Belgium,0.84,0.99,1.03,0.93,1.01,0.97,0.97,0.92,0.99,0.96,NaN,-,1.50%
2,Bulgaria,0.16,0.19,0.26,0.19,0.17,0.16,0.16,0.32,0.58,0.67,NaN,↑,17.20%

In [86]:
hospital_sulfonamides_trimethoprim[:3]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,0.04,0.05,NaN,NaN,NaN
1,Belgium,NaN,NaN,NaN,NaN,0.04,0.04,0.04,0.04,0.04,0.04,NaN,NaN,NaN
2,Bulgaria,0.01,0.01,0.01,0.01,0.01,0.00,0.01,0.01,0.01,0.01,-7.0%,NaN,NaN

In [87]:
hospital_tetracyclines[:10]

,Country name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Compound annual growth rate (CAGR),Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,0.06,0.05,NaN,NaN,NaN,NaN
1,Belgium,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,-1.4%,NaN,NaN,NaN
2,Bulgaria,0.02,0.02,0.02,0.02,0.02,0.01,0.01,0.02,0.04,0.06,12.1%,NaN,NaN,NaN
3,Croatia,0.06,0.05,0.04,0.04,0.04,0.04,0.03,0.04,0.03,0.03,-9.2%,NaN,NaN,NaN
4,Czechia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05,NaN,NaN,NaN,NaN
5,Denmark,0.04,0.03,0.04,0.04,0.04,0.04,0.05,0.06,0.05,0.05,3.6%,NaN,NaN,NaN
6,Estonia,0.09,0.08,0.06,0.06,0.04,0.04,0.04,0.03,0.04,0.03,-10.1%,NaN,NaN,NaN
7,Finland (a),0.24,0.22,0.21,0.19,0.18,0.16,0.16,0.18,0.12,0.10,-8.9%,NaN,NaN,NaN
8,France,0.01,0.02,0.03,0.02,0.02,0.03,0.03,0.04,0.05,0.06,22.7%,NaN,NaN,NaN
9,Greece,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06,0.06,0.08,5.0%,NaN,NaN,NaN

### Observations
* I should compile all these dataframes into a list
* CAGR column should be deleted
* Same for columns "Unnamed: 12", "Unnamed: 13" and "Unnamed: 14"
* Rows with NaNs should be deleted
* Luxembourg should be deleted since data acquisition has been inconsistent
* Rename 'Czech Republic' to 'Czechia' for consistency
* Some Finland data includes nursing homes and some does not - we drop the Finland column.

In [88]:
list_of_drug_dfs = [community_betalactams_main, community_betalactams_others,
                    community_macrolides_lincosamides_streptogramins, community_others, community_quinolones, 
                    community_sulfonamides_trimethoprim, community_tetracyclines, hospital_betalactams_main, hospital_betalactams_others, 
                    hospital_carbapenems, hospital_macrolides_lincosamides_streptogramins, hospital_others, 
                    hospital_polymyxins, hospital_quinolones, hospital_reserve, hospital_sulfonamides_trimethoprim, 
                    hospital_tetracyclines]

In [89]:
def cleanup(table):
    # Remove the 'Unnamed' columns:
    table.drop(table.columns[table.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
    # Remove whitespace from column headers
    table.columns = table.columns.str.strip()
    
    # Remove 'Trend' and 'Time series' columns if present
    if 'Trend' in table.columns:
        table.drop('Trend', axis = 1, inplace = True)
    # Delete the "Time series" column if present:
    if 'Time series\n2012-2021'in table.columns:
        table.drop('Time series\n2012-2021', axis = 1, inplace = True)
    
    # Drop any rows that contain NaN values:
    table.dropna(axis = 0, inplace = True)
    
    # Drop the CAGR column:
    table.drop(table.columns[table.columns.str.contains('CAGR',case = True)],axis = 1, inplace = True)
    
    # Swap all instances of 'Czech Republic' to 'Czechia'
    table.loc[table['Country name'].str.contains('Czech Republic', case=False), 'Country name'] = 'Czechia'
   
    # Delete Luxembourg, UK, Finland and EU rows
    table.drop(table.index[table['Country name'].str.contains('Luxembourg', case = True)], axis = 0, inplace = True)
    table.drop(table.index[table['Country name'].str.contains('United Kingdom', case = True)], axis = 0, inplace = True)
    table.drop(table.index[table['Country name'].str.contains('EU', case = True)], axis = 0, inplace = True)
    table.drop(table.index[table['Country name'].str.contains('Finland', case = True)], axis = 0, inplace = True)
    return table

In [90]:
cleaned_up_dfs = [cleanup(table) for table in list_of_drug_dfs];

In [91]:
country_dict = {}
count = 0
for table in cleaned_up_dfs:
    count += 1
    for country_name in table['Country name']:
        if country_name in country_dict.keys():
            country_dict[country_name] += 1
        else:
            country_dict[country_name] = 1
print(country_dict)
print("The total number of dataframes is", count)

{'Austria': 7, 'Belgium': 15, 'Bulgaria': 16, 'Croatia': 17, 'Denmark': 16, 'Estonia': 17, 'France': 17, 'Germany': 7, 'Greece': 17, 'Hungary': 17, 'Ireland': 17, 'Italy': 17, 'Latvia': 17, 'Lithuania': 16, 'Malta': 17, 'Netherlands': 17, 'Norway': 17, 'Poland': 7, 'Portugal': 16, 'Slovakia': 17, 'Slovenia': 17, 'Sweden': 17, 'Portugal ': 1}
The total number of dataframes is 17

In [92]:
final_list =[]
for key in country_dict:
    if country_dict[key] == count:
        final_list.append(key)
print("The list of countries that are present throughout the whole dataset is:", final_list)

The list of countries that are present throughout the whole dataset is: ['Croatia', 'Estonia', 'France', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Malta', 'Netherlands', 'Norway', 'Slovakia', 'Slovenia', 'Sweden']

So, the analysis can only be concerned with these countries -- since they are the ones we have data for.

In [93]:
cleaned_up_dfs

[   Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria   4.5   5.3   4.7   4.7   4.7   5.1   4.7   4.2   3.3   3.5
 1       Belgium  11.5   9.9   9.9  10.1  10.2   9.7  10.1   9.8   7.0   7.5
 2      Bulgaria   5.3   5.7   5.6   5.5   4.7   5.4   5.5   5.4   4.7   4.8
 3       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 6       Denmark   9.5   9.8   9.7   9.9   9.8   9.5   9.2   8.9   8.1   8.2
 7       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 9        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 10      Germany   3.3   3.5   3.4   3.3   3.4   3.8   3.7   4.0   3.1   2.8
 11       Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 12      Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 14      Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 15        Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 16       Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 17    Lithuania   6.2   7.2   6.1   6.5   6.5   6.7   6.5   6.3   4.9   5.5
 19        Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 20  Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 21       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 22       Poland   6.2   6.4   6.0   7.1   6.8   6.6   6.8   6.4   4.4   5.2
 23     Portugal   8.4   7.6   7.9   8.3   8.6   8.7   9.2   9.1   6.7   6.6
 25     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 26     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 28       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  1.58  1.95  1.48  1.44  1.41  1.51  1.40  1.27  0.96  1.04
 1       Belgium  1.53  1.53  1.42  1.44  1.32  1.17  1.25  1.20  0.80  0.80
 2      Bulgaria  2.44  2.80  3.38  3.90  3.84  4.11  4.48  4.28  3.97  4.54
 3       Croatia  3.53  2.99  2.81  2.74  2.49  2.47  2.52  2.55  2.09  2.36
 6       Denmark  0.03  0.03  0.03  0.03  0.03  0.03  0.03  0.03  0.03  0.03
 7       Estonia  0.99  1.10  1.14  1.22  1.16  1.18  1.18  1.19  1.02  0.93
 9        France  2.39  2.25  2.05  2.12  1.94  1.60  1.40  1.28  0.88  0.89
 10      Germany  2.82  3.22  3.01  3.11  3.03  2.81  2.49  2.36  1.68  1.44
 11       Greece  6.56  7.40  7.29  7.53  7.43  7.70  7.88  7.59  5.76  4.38
 12      Hungary  1.77  1.81  1.87  1.98  2.06  2.10  2.13  2.06  1.38  1.31
 14      Ireland  1.24  1.36  1.10  1.16  1.17  1.08  1.14  1.17  0.96  0.94
 15        Italy  2.36  2.48  2.34  2.33  2.26  1.94  2.05  2.27  1.68  1.63
 16       Latvia  0.47  0.52  0.48  0.52  0.57  0.66  0.61  0.62  0.41  0.40
 17    Lithuania  0.92  1.21  1.07  1.16  1.23  1.29  1.33  1.34  1.18  1.22
 19        Malta  5.27  5.52  4.57  4.11  3.57  3.12  2.63  2.86  2.00  1.45
 20  Netherlands  0.04  0.04  0.04  0.04  0.03  0.03  0.03  0.03  0.03  0.03
 21       Norway  0.11  0.11  0.09  0.08  0.07  0.06  0.06  0.05  0.05  0.05
 22       Poland  2.20  2.50  2.37  2.87  2.75  3.99  3.01  3.51  2.32  2.26
 23     Portugal  1.55  1.43  1.44  1.56  1.54  1.64  1.62  1.64  1.36  1.45
 25     Slovakia  3.49  4.51  4.37  4.71  4.62  4.58  6.21  4.86  3.30  3.52
 26     Slovenia  0.30  0.30  0.28  0.31  0.33  0.37  0.32  0.39  0.40  0.47
 28       Sweden  0.18  0.16  0.15  0.14  0.14  0.08  0.07  0.06  0.05  0.05,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  3.19  3.59  3.04  3.06  2.74  2.81  2.25  2.04  1.42  1.39
 1       Belgium  3.40  3.34  3.40  3.63  3.62  3.41  3.56  3.50  2.65  2.65
 2      Bulgaria  3.16  3.44  3.93  3.87  3.67  3.82  4.00  4.01  5.72  5.50
 3       Croatia  2.97  2.80  2.91  3.10  2.71  2.75  2.83  2.79  2.44  3.05
 6       Denmark  2.25  1.84  1.84  1.84  1.80  1.62  1.47  1.43  1.20  1.17
 7       Estonia  2.46  2.48  2.40  2.45  2.27  2.26  2.32  2.33  1.80  1.74
 9        France  3.70  3.50  3.01  3.23  2.97  3.04  2.89  2.81  2.34  2.37
 10      Germany  2.68  2.80  2.48  2.40  2.27  2.14  1.94  1.83  1.31  1.15
 11       Greece  7.81  7.22  7.88  7.50  6.07  6.98  6.36  6.60  5.06  3.62
 12      Hungary  2.73  2.82  3.13  3.30  2.82  2.80  2.83  2.79  2.24  2.91
 14      Ireland  4.16  4.38  4.15  4.20  4.38  4.19  4.04  3.86  2.93  2.51
 15        Italy  4.68  4.80  4.66  4.61  4.34  3.75  3.87  4.06  3.56  3.30
 16       Latvia  1.53  1.73  1.61  1.83  1.81  1.97  2.05  2.13  1.65  1.65
 17    Lithuania  1.89  2.38  1.87  1.92  1.97  2.07  2.11  2.11  1.67  1.49
 19        Malta  3.70  3.96  3.77  4.00  3.91  4.46  4.38  4.24  2.45  2.38
 20  Netherlands  1.50  1.39  1.35  1.39  1.37  1.38  1.45  1.45  1.36  1.31
 21       Norway  2.00  1.69  1.47  1.31  1.15  1.01  0.89  0.87  0.65  0.58
 22       Poland  3.53  3.88  3.79  4.60  4.19  4.46  6.01  3.92  2.76  3.66
 23     Portugal  3.21  2.75  2.79  3.06  3.09  2.44  2.68  3.12  2.03  1.91
 25     Slovakia  4.91  5.89  5.56  6.20  5.44  4.68  4.72  4.58  3.30  4.30
 26     Slovenia  1.79  1.78  1.76  1.85  1.59  1.68  1.78  1.73  1.34  1.26
 28       Sweden  0.63  0.62  0.61  0.60  0.54  0.54  0.50  0.52  0.50  0.46,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  0.28  0.35  0.33  0.33  0.34  0.38  0.35  0.36  0.30  0.22
 1       Belgium  2.63  2.71  2.76  2.73  2.75  2.51  2.51  2.60  2.50  2.54
 2      Bulgaria  0.00  0.00  0.00  0.00  0.10  0.11  0.02  0.01  0.01  0.01
 3       Croatia  0.68  0.72  0.78  0.83  0.88  0.73  0.84  0.92  0.91  1.04
 6       Denmark  0.78  0.76  0.67  0.73  0.73  0.58  0.47  0.61  0.64  0.67
 7       Estonia  0.76  0.75  0.75  0.77  0.77  0.54  0.55  0.56  0.45  0.56
 9        France  0.46  0.45  0.41  0.46  0.45  0.51  0.44  0.45  0.38  0.43
 10      Germany  0.52  0.53  0.55  0.52  0.51  0.48  0.47  0.51  0.52  0.47
 11       Greece  0.55  0.67  0.67  0.77  0.84  0.92  0.90  0.80  0.77  0.84
 12      Hungary  0.21  0.25  0.26  0.21  0.09  0.09  0.27  0.30  0.29  0.29
 14      Ireland  0.04  0.04  0.03  0.04  0.04  0.03  1.36  1.40  1.40  1.37
 15        Italy  0.68  0.70  0.71  0.71  0.70  0.65  0.68  0.74  0.75  0.80
 16       Latvia  0.26  0.29  0.33  0.33  0.30  0.71  0.69  0.74  0.78  0.83
 17    Lithuania  1.33  1.37  1.44  1.42  1.43  1.17  1.15  1.28  1.41  1.30
 19        Malta  0.34  0.40  0.48  0.99  0.31  0.40  0.48  0.55  0.84  0.71
 20  Netherlands  1.43  1.43  1.47  1.47  1.47  1.45  1.45  1.40  1.34  1.34
 21       Norway  3.29  3.40  3.58  3.74  3.87  3.94  3.94  3.28  3.85  3.92
 22       Poland  2.87  3.45  3.55  3.88  2.62  4.32  2.92  4.35  4.31  4.44
 23     Portugal  1.44  1.00  1.10  1.13  1.15  1.13  1.24  1.29  1.27  1.30
 25     Slovakia  0.03  0.05  0.06  0.06  0.08  0.05  0.06  0.07  0.07  0.07
 26     Slovenia  0.11  0.19  0.26  0.36  0.36  0.40  0.36  0.49  0.47  0.54
 28       Sweden  1.62  1.61  1.60  1.59  1.56  1.52  1.50  1.28  1.20  1.17,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  1.30  1.47  1.30  1.31  1.20  1.23  1.04  0.73  0.57  0.52
 1       Belgium  2.77  2.64  2.55  2.57  2.40  2.17  1.16  0.57  0.46  0.45
 2      Bulgaria  2.40  2.52  2.87  2.83  2.78  2.86  2.83  2.76  3.35  3.92
 3       Croatia  1.49  1.47  1.50  1.50  1.49  1.50  1.48  1.36  1.22  1.44
 6       Denmark  0.55  0.52  0.50  0.49  0.48  0.44  0.41  0.37  0.33  0.32
 7       Estonia  0.85  0.89  0.90  0.92  0.85  0.79  0.75  0.65  0.72  0.59
 9        France  1.92  1.84  1.75  1.60  1.51  1.37  1.30  1.21  1.09  0.99
 10      Germany  1.45  1.42  1.34  1.33  1.24  1.11  0.96  0.63  0.49  0.43
 11       Greece  2.36  2.06  2.56  2.64  2.61  2.60  2.94  3.04  2.61  2.16
 12      Hungary  1.97  2.11  2.43  2.71  2.38  2.40  2.31  1.93  1.41  1.42
 14      Ireland  0.87  0.87  0.84  0.92  0.87  0.81  0.76  0.55  0.42  0.38
 15        Italy  3.48  3.55  3.41  3.37  3.23  2.68  2.65  1.99  1.67  1.62
 16       Latvia  1.03  1.05  1.05  1.05  1.05  1.03  0.94  0.85  0.77  0.71
 17    Lithuania  1.00  0.96  0.91  0.91  0.88  0.87  0.88  0.82  0.73  0.66
 19        Malta  2.01  2.92  3.06  2.64  2.37  2.18  2.27  1.89  1.36  1.31
 20  Netherlands  0.81  0.76  0.79  0.77  0.75  0.73  0.73  0.67  0.64  0.64
 21       Norway  0.56  0.54  0.50  0.46  0.41  0.35  0.32  0.28  0.24  0.22
 22       Poland  1.19  1.18  1.21  1.40  1.42  1.49  1.48  1.35  1.15  1.27
 23     Portugal  2.47  2.18  2.12  2.05  1.92  1.75  1.71  1.54  1.21  1.17
 25     Slovakia  1.95  2.18  0.63  2.40  2.26  2.12  2.07  1.47  1.14  1.17
 26     Slovenia  1.08  1.10  1.11  1.16  1.14  1.11  1.11  0.99  0.84  0.85
 28       Sweden  0.75  0.71  0.69  0.68  0.66  0.63  0.61  0.56  0.49  0.49,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  0.22  0.23  0.20  0.19  0.20  0.22  0.20  0.22  0.22  0.23
 2      Bulgaria  0.82  0.83  0.84  0.79  0.78  0.85  0.86  0.78  0.64  0.65
 3       Croatia  0.67  0.67  0.65  0.63  0.59  0.55  0.50  0.49  0.44  0.48
 6       Denmark  0.77  0.75  0.76  0.73  0.72  0.71  0.67  0.58  0.54  0.52
 7       Estonia  0.39  0.40  0.38  0.43  0.40  0.42  0.44  0.41  0.29  0.32
 9        France  0.44  0.27  0.48  0.41  0.41  0.41  0.41  0.43  0.46  0.51
 10      Germany  0.55  0.53  0.50  0.47  0.46  0.46  0.43  0.51  0.44  0.49
 11       Greece  0.32  0.32  0.34  0.41  0.37  0.32  0.30  0.33  0.44  0.32
 12      Hungary  0.53  0.53  0.50  0.51  0.48  0.44  0.44  0.44  0.38  0.38
 14      Ireland  1.16  0.98  1.00  1.04  1.10  0.88  1.02  1.00  1.04  0.94
 15        Italy  0.36  0.35  0.34  0.34  0.37  0.66  0.73  0.88  0.83  0.83
 16       Latvia  0.95  0.97  0.85  0.84  0.81  0.82  0.74  0.78  0.51  0.42
 17    Lithuania  0.37  0.39  0.36  0.36  0.80  0.81  0.75  0.52  0.52  0.20
 19        Malta  0.20  0.19  0.27  0.24  0.26  0.38  0.32  0.41  0.30  0.46
 20  Netherlands  0.52  0.47  0.44  0.43  0.42  0.42  0.43  0.46  0.45  0.45
 21       Norway  0.68  0.67  0.68  0.67  0.66  0.65  0.68  0.72  0.70  0.70
 22       Poland  1.50  0.57  0.54  0.58  0.56  0.48  0.53  0.52  0.42  0.24
 23     Portugal  0.53  0.44  0.44  0.43  0.42  0.41  0.35  0.37  0.35  0.39
 25     Slovakia  0.34  0.38  0.41  0.45  1.19  0.38  0.38  0.46  0.41  0.45
 26     Slovenia  0.94  0.90  0.82  0.79  0.74  0.68  0.70  0.63  0.53  0.53
 28       Sweden  0.44  0.42  0.40  0.40  0.38  0.27  0.28  0.28  0.27  0.27,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Austria  1.08  1.27  1.06  0.99  0.86  0.63  0.36  0.32  0.28  0.34
 1       Belgium  2.11  2.16  2.10  2.03  1.99  1.92  1.87  1.86  1.63  1.81
 2      Bulgaria  1.77  1.76  1.79  1.70  1.68  1.63  1.62  1.68  2.19  2.56
 3       Croatia  1.19  1.19  1.12  1.14  1.02  1.00  0.98  0.93  0.79  0.98
 6       Denmark  1.76  1.96  1.66  1.61  1.61  1.42  1.40  1.48  1.69  1.64
 7       Estonia  1.80  1.61  1.46  1.44  1.56  1.28  1.24  1.35  1.35  1.30
 9        France  3.30  3.35  3.21  3.26  3.24  3.00  3.14  3.20  2.91  3.09
 10      Germany  2.34  2.42  2.11  1.97  1.90  1.76  1.64  1.56  1.45  1.31
 11       Greece  1.91  1.83  2.37  2.58  2.69  2.79  2.94  3.04  2.98  2.94
 12      Hungary  1.18  1.18  1.18  1.21  1.11  1.07  1.11  1.13  1.17  1.23
 14      Ireland  2.93  2.96  2.72  2.57  2.54  2.80  2.61  2.99  2.97  2.96
 15        Italy  0.54  0.56  0.58  0.55  0.56  0.48  0.52  0.56  0.58  0.65
 16       Latvia  2.52  2.35  2.19  2.18  2.18  2.17  2.06  2.24  2.23  2.58
 17    Lithuania  1.53  1.54  1.37  1.33  1.45  1.40  1.34  1.42  1.49  1.36
 19        Malta  1.68  1.00  1.20  0.75  1.77  1.60  1.50  1.74  2.08  2.10
 20  Netherlands  2.49  2.33  2.23  2.25  2.10  1.98  1.94  1.83  1.54  1.42
 21       Norway  3.45  3.24  3.12  3.08  2.89  2.73  2.62  2.71  2.48  2.50
 22       Poland  2.39  2.51  2.40  2.39  2.34  2.39  2.28  2.16  1.75  1.71
 23     Portugal  1.08  0.75  0.83  0.83  0.81  0.83  0.85  0.86  0.81  0.94
 25     Slovakia  1.37  1.58  1.67  1.73  1.67  1.62  1.70  1.68  1.66  1.73
 26     Slovenia  0.43  0.46  0.45  0.42  0.49  0.47  0.51  0.54  0.53  0.54
 28       Sweden  3.44  2.85  2.66  2.54  2.40  2.35  2.16  2.14  1.92  1.84,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 1       Belgium  0.79  0.75  0.74  0.76  0.75  0.74  0.76  0.74  0.64  0.64
 2      Bulgaria  0.11  0.10  0.11  0.10  0.10  0.10  0.11  0.12  0.13  0.12
 3       Croatia  0.50  0.44  0.45  0.46  0.45  0.45  0.47  0.50  0.39  0.47
 5       Denmark  0.80  0.94  0.99  1.00  1.00  1.00  1.07  1.00  0.98  1.06
 6       Estonia  0.46  0.45  0.44  0.46  0.49  0.51  0.55  0.54  0.58  0.53
 8        France  0.85  0.85  0.86  0.87  0.86  0.84  0.83  0.84  0.71  0.74
 9        Greece  0.32  0.50  0.51  0.55  0.80  0.78  0.29  0.30  0.30  0.33
 10      Hungary  0.32  0.31  0.32  0.28  0.29  0.29  0.27  0.27  0.23  0.22
 12      Ireland  0.73  0.69  0.58  0.80  0.78  0.76  0.85  0.87  0.68  0.72
 13        Italy  0.59  0.60  0.59  0.62  0.62  0.57  0.55  0.58  0.46  0.45
 14       Latvia  0.38  0.38  0.38  0.41  0.38  0.42  0.43  0.44  0.40  0.25
 15    Lithuania  0.62  0.69  0.64  0.67  0.68  0.67  0.71  0.64  0.61  0.68
 17        Malta  0.38  0.54  0.64  0.85  1.05  1.31  0.84  0.77  0.87  0.70
 18  Netherlands  0.34  0.33  0.33  0.33  0.33  0.32  0.32  0.30  0.27  0.24
 19       Norway  0.64  0.63  0.67  0.68  0.68  0.69  0.62  0.63  0.55  0.54
 21     Portugal  0.44  0.46  0.45  0.47  0.49  0.47  0.49  0.50  0.51  0.55
 23     Slovakia  0.71  0.61  0.78  0.68  0.78  0.30  0.31  0.30  0.29  0.27
 24     Slovenia  0.54  0.57  0.57  0.60  0.62  0.63  0.64  0.65  0.58  0.61
 26       Sweden  0.78  0.81  0.77  0.84  0.83  0.82  0.99  0.83  0.80  0.80,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 1       Belgium  0.38  0.39  0.38  0.39  0.38  0.37  0.38  0.38  0.33  0.34
 2      Bulgaria  0.81  0.77  0.79  0.74  0.97  0.91  0.91  0.94  1.00  1.21
 3       Croatia  0.54  0.49  0.52  0.54  0.50  0.55  0.53  0.56  0.50  0.60
 5       Denmark  0.29  0.35  0.39  0.29  0.26  0.30  0.25  0.23  0.21  0.20
 6       Estonia  0.54  0.54  0.56  0.57  0.55  0.55  0.51  0.51  0.52  0.46
 8        France  0.28  0.30  0.31  0.32  0.33  0.32  0.33  0.33  0.32  0.33
 9        Greece  0.53  0.52  0.50  0.51  0.52  0.50  0.54  0.52  0.54  0.57
 10      Hungary  0.29  0.30  0.31  0.33  0.32  0.35  0.37  0.38  0.43  0.41
 12      Ireland  0.14  0.16  0.17  0.18  0.17  0.19  0.20  0.21  0.19  0.21
 13        Italy  0.42  0.42  0.41  0.36  0.30  0.39  0.45  0.46  0.45  0.38
 14       Latvia  0.65  0.66  0.66  0.67  0.64  0.64  0.60  0.66  0.68  0.59
 15    Lithuania  0.56  0.62  0.66  0.73  0.74  0.78  0.77  0.83  0.81  0.72
 17        Malta  0.24  0.24  0.24  0.23  0.22  0.28  0.30  0.26  0.25  0.20
 18  Netherlands  0.17  0.18  0.19  0.20  0.20  0.21  0.23  0.23  0.23  0.23
 19       Norway  0.31  0.30  0.28  0.27  0.26  0.27  0.26  0.25  0.23  0.24
 21     Portugal  0.40  0.41  0.40  0.40  0.40  0.40  0.39  0.39  0.42  0.47
 23     Slovakia  0.53  0.64  0.69  0.74  0.75  0.42  0.50  0.41  0.39  0.47
 24     Slovenia  0.31  0.30  0.30  0.30  0.30  0.31  0.31  0.32  0.29  0.32
 26       Sweden  0.18  0.19  0.16  0.16  0.16  0.16  0.17  0.16  0.16  0.16,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 1       Belgium  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.04  0.04
 2      Bulgaria  0.01  0.01  0.01  0.01  0.02  0.03  0.03  0.04  0.10  0.12
 3       Croatia  0.05  0.05  0.05  0.06  0.06  0.08  0.07  0.08  0.09  0.12
 5       Denmark  0.04  0.06  0.06  0.06  0.05  0.05  0.05  0.05  0.05  0.05
 6       Estonia  0.03  0.03  0.04  0.04  0.06  0.05  0.06  0.07  0.08  0.08
 8        France  0.02  0.03  0.03  0.03  0.03  0.03  0.03  0.03  0.03  0.03
 9        Greece  0.10  0.10  0.10  0.10  0.12  0.12  0.12  0.13  0.14  0.17
 10      Hungary  0.03  0.03  0.04  0.04  0.04  0.04  0.05  0.05  0.07  0.07
 12      Ireland  0.04  0.06  0.07  0.06  0.05  0.05  0.04  0.05  0.04  0.05
 13        Italy  0.06  0.06  0.06  0.04  0.03  0.03  0.04  0.05  0.06  0.06
 14       Latvia  0.02  0.02  0.02  0.03  0.03  0.03  0.03  0.03  0.05  0.04
 15    Lithuania  0.02  0.02  0.03  0.04  0.04  0.04  0.04  0.05  0.05  0.06
 17        Malta  0.04  0.05  0.07  0.07  0.08  0.12  0.09  0.08  0.09  0.08
 18  Netherlands  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01
 19       Norway  0.03  0.03  0.03  0.03  0.03  0.03  0.02  0.02  0.02  0.02
 21    Portugal   0.11  0.11  0.11  0.10  0.09  0.08  0.08  0.08  0.08  0.09
 23     Slovakia  0.02  0.03  0.03  0.03  0.04  0.04  0.05  0.04  0.05  0.06
 24     Slovenia  0.07  0.06  0.06  0.06  0.06  0.06  0.06  0.05  0.05  0.06
 26       Sweden  0.04  0.04  0.04  0.04  0.04  0.04  0.04  0.04  0.04  0.04,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 1       Belgium  0.10  0.10  0.10  0.11  0.11  0.11  0.11  0.12  0.11  0.09
 2      Bulgaria  0.13  0.14  0.14  0.11  0.11  0.11  0.13  0.12  0.23  0.13
 3       Croatia  0.16  0.15  0.14  0.15  0.15  0.16  0.16  0.18  0.19  0.21
 5       Denmark  0.09  0.09  0.09  0.10  0.11  0.13  0.14  0.14  0.12  0.09
 6       Estonia  0.22  0.16  0.18  0.16  0.13  0.16  0.17  0.16  0.17  0.12
 8        France  0.11  0.10  0.12  0.11  0.11  0.12  0.11  0.13  0.16  0.12
 9        Greece  0.17  0.18  0.19  0.18  0.15  0.13  0.14  0.14  0.20  0.08
 10      Hungary  0.12  0.11  0.12  0.13  0.11  0.12  0.12  0.13  0.19  0.15
 12      Ireland  0.26  0.28  0.28  0.27  0.26  0.24  0.24  0.22  0.18  0.15
 13        Italy  0.20  0.19  0.20  0.19  0.18  0.18  0.18  0.20  0.31  0.11
 14       Latvia  0.15  0.15  0.16  0.17  0.13  0.14  0.13  0.14  0.18  0.09
 15    Lithuania  0.06  0.07  0.10  0.06  0.07  0.08  0.08  0.08  0.10  0.06
 17        Malta  0.21  0.22  0.25  0.35  0.32  0.33  0.24  0.25  0.24  0.17
 18  Netherlands  0.07  0.07  0.06  0.06  0.06  0.06  0.06  0.05  0.05  0.04
 19       Norway  0.08  0.08  0.07  0.07  0.07  0.07  0.06  0.06  0.05  0.05
 21     Portugal  0.16  0.16  0.15  0.16  0.17  0.16  0.16  0.16  0.17  0.16
 23     Slovakia  0.10  0.15  0.19  0.15  0.14  0.13  0.14  0.14  0.16  0.16
 24     Slovenia  0.12  0.12  0.12  0.14  0.13  0.13  0.13  0.13  0.10  0.10
 26       Sweden  0.06  0.07  0.06  0.07  0.06  0.07  0.06  0.06  0.06  0.05,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 1       Belgium  0.15  0.14  0.14  0.14  0.13  0.13  0.12  0.12  0.11  0.11
 2      Bulgaria  0.01  0.08  0.02  0.10  0.11  0.14  0.18  0.15  0.12  0.08
 3       Croatia  0.13  0.13  0.15  0.16  0.17  0.19  0.24  0.22  0.20  0.27
 5       Denmark  0.14  0.14  0.14  0.13  0.13  0.14  0.13  0.13  0.12  0.11
 6       Estonia  0.16  0.16  0.16  0.14  0.15  0.11  0.11  0.11  0.11  0.09
 8        France  0.12  0.13  0.13  0.13  0.13  0.12  0.14  0.15  0.15  0.16
 9        Greece  0.27  0.28  0.29  0.27  0.31  0.31  0.32  0.36  0.36  0.40
 10      Hungary  0.07  0.06  0.07  0.06  0.06  0.07  0.08  0.08  0.11  0.11
 12      Ireland  0.17  0.21  0.21  0.19  0.18  0.18  0.19  0.19  0.17  0.17
 13        Italy  0.37  0.14  0.15  0.15  0.17  0.15  0.17  0.18  0.18  0.17
 14       Latvia  0.16  0.17  0.18  0.18  0.19  0.21  0.22  0.20  0.22  0.19
 15    Lithuania  0.17  0.19  0.18  0.20  0.23  0.24  0.27  0.31  0.34  0.24
 17        Malta  0.11  0.13  0.17  0.22  0.17  0.26  0.30  0.26  0.29  0.28
 18  Netherlands  0.07  0.07  0.07  0.07  0.07  0.07  0.07  0.07  0.07  0.07
 19       Norway  0.12  0.11  0.10  0.09  0.09  0.09  0.09  0.09  0.09  0.08
 21     Portugal  0.11  0.16  0.11  0.12  0.12  0.17  0.10  0.11  0.12  0.12
 23     Slovakia  0.16  0.22  0.20  0.18  0.19  0.19  0.43  0.20  0.13  0.17
 24     Slovenia  0.10  0.09  0.10  0.11  0.11  0.11  0.11  0.11  0.11  0.13

In [94]:
def country_wiper(table):
    for table in cleaned_up_dfs:
        for country in table['Country name']:
            if country not in final_list:
                table.drop(table.index[table['Country name'].str.contains(country, case = True)], axis = 0, inplace = True)
        table = table.reset_index(drop=True)
        return table

In [95]:
final_country_data = [country_wiper(table) for table in cleaned_up_dfs]

In [96]:
print(final_country_data)

[   Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4]

In [97]:
final_country_data

[   Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4,
    Country name  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
 0       Croatia   7.7   7.8   8.0   8.1   7.9   7.8   7.8   7.9   6.2   6.9
 1       Estonia   3.1   3.1   3.2   3.3   3.4   3.5   3.7   3.7   3.2   3.2
 2        France  11.7  12.4  12.2  12.7  13.3  13.0  13.3  13.3  10.1  11.0
 3        Greece   8.6   8.4   8.0   9.8  10.9  10.8  11.1  11.0   8.7   7.4
 4       Hungary   4.6   4.7   4.6   4.8   4.4   4.5   4.6   4.6   3.2   3.3
 5       Ireland   9.0   9.5   9.7  11.3  10.3   9.5   9.7  10.0   7.4   7.2
 6         Italy  10.3  10.8  10.5  10.4  10.3   8.8   8.9   9.2   7.4   7.1
 7        Latvia   4.2   4.4   4.1   4.4   4.3   4.7   4.4   4.6   3.6   3.5
 8         Malta   6.0   6.4   6.5   5.8   5.9   7.3   6.1   6.7   5.2   5.5
 9   Netherlands   3.2   3.2   3.1   3.1   3.1   2.9   2.9   2.8   2.4   2.4
 10       Norway   6.4   6.2   6.1   6.1   5.8   5.6   5.5   5.7   4.8   4.9
 11     Slovakia   5.8   6.5   6.2   6.4   6.0   5.1   5.0   4.8   3.3   3.3
 12     Slovenia   7.1   7.2   6.9   7.0   6.8   6.9   6.9   6.7   4.7   4.6
 13       Sweden   6.6   6.3   6.4   6.0   6.0   5.9   5.7   5.5   4.5   4.4]

# What do each of the tables mean?
### There are several tables for medicines that are administered in both the 'community' and 'hospital' categories:
1. **Beta-lactams**: <br>This is a broad class of antibiotics that includes:
    * penicillins, 
    * cephalosporins, 
    * carbapenems, and 
    * monobactams. 
    They work by inhibiting the synthesis of bacterial cell walls, leading to the death of the bacteria. 
    They are commonly used to treat a wide range of infections, from relatively minor infections like strep throat and ear infections to serious conditions like sepsis. Their specific use depends on the subclass and the individual medication.

2. **Macrolides, Lincosamides, Streptogramins**: <br> These antibiotics work by inhibiting protein synthesis in bacteria, stopping their growth. 
    * **Macrolides (like erythromycin and azithromycin)** are often used for respiratory tract and soft-tissue infections. 
    * **Lincosamides (like clindamycin)** can be used for skin and soft tissue infections, especially those caused by staphylococcus and streptococcus bacteria. 
    * **Streptogramins** (like quinupristin/dalfopristin) are typically reserved for serious, hospital-acquired infections like vancomycin-resistant Enterococcus faecium.

3. **Quinolones**: <br>
Also known as fluoroquinolones, these antibiotics inhibit bacterial DNA synthesis. They are broad-spectrum antibiotics used for various types of infections:
    * urinary tract infections, 
    * respiratory infections, and 
    * some types of gastrointestinal infections. 
    Examples include ciprofloxacin and levofloxacin. Their use has been somewhat limited due to concerns about side effects and increasing bacterial resistance.


4. **Sulfonamides, Trimethoprim**: <br>
These antibiotics inhibit folic acid synthesis in bacteria, which is necessary for their growth and reproduction. 
    * Sulfonamides (like sulfamethoxazole) and trimethoprim are often used together (as in the combination drug co-trimoxazole) to treat:
        * urinary tract infections, 
        * ear infections, 
        * bronchitis, and 
        * some types of pneumonia. 
    * They are also used for the prevention and treatment of Pneumocystis jiroveci pneumonia in immunocompromised patients.

5. **Tetracyclines**: <br>
These antibiotics inhibit bacterial protein synthesis. They are used for a wide range of infections, including:
    * acne, 
    * chlamydia, 
    * Lyme disease, and 
    * infections of the respiratory tract. 
Examples include doxycycline and minocycline.

### And there are tables for medicines administered in the hospital only.
These tables are for: <br>
6. **Polymyxins:** <br> 
* These antibiotics disrupt the bacterial cell membrane, leading to the death of the bacteria. 
* Polymyxins (like colistin) are used to treat infections caused by multidrug-resistant Gram-negative bacteria. 
* They are often considered antibiotics of **last resort due to their potential for nephrotoxicity and neurotoxicity**.


7. **Reserve** <br>
* Reserve antibiotics are last-resort antibiotics that should only be used to treat severe infections caused by multidrug-resistant pathogens.

## Procedure to follow
### For the antibiotics that are administered in the hospital and in the community, I will add those tables:
Example:
`quinolones = hospital_quinolones + community_quinolones`

I will perform this for:
* betalactams
* macrolides, lincosamides and streptogamins
* sulfonamides, trimetoprim
* tetracyclins
* quinolones
* others

`betalactams = hopital_betalactams_main + hospital_betalactams_other + community_betalactams_main + community_betalactams__other`